FROM infinispan/server:10.0.1.Final

ADD *.properties /opt/infinispan/server/conf/
ADD jgroups-tcp.xml /opt/infinispan/server/conf/jgroups-tcp.xml
COPY infinispan-local.xml /opt/infinispan/server/conf/infinispan.xml