package com.redhat.quotegame.processors
unit QuotePriceUpdaterService

import com.redhat.quotegame.model.Order
import com.redhat.quotegame.model.OrderType
import java.util.List

rule "com.redhat.quotegame.processors.QuotePriceUpdaterService.IncomingOrder"
when
    $list : List( size == 3 ) from collect /orderStream[ orderType == OrderType.BUY ]
then
    System.out.println(drools.getRule().getName());
    for ( Object $o : $list){
        System.out.println("Retracting "+$o);
    }
end




